"""Build a dependency-free legal site; --release refuses missing provider details."""
import argparse, html, json
from pathlib import Path

root = Path(__file__).parent
parser = argparse.ArgumentParser()
parser.add_argument('--release', action='store_true')
args = parser.parse_args()
config = json.loads((root / 'provider.json').read_text())
required = ['legal_name', 'contact_email', 'website_url']
missing = [key for key in required if not config.get(key, '').strip()]
if args.release and missing:
    raise SystemExit('Publication blocked: missing ' + ', '.join(missing))
def value(key, fallback):
    return html.escape(config.get(key) or fallback)
provider = value('legal_name', '[Legal provider required]')
address = value('address', '')
country = value('country', '')
email = value('contact_email', '[Public contact email required]')
contact = f'<a href="mailto:{email}">{email}</a>' if config.get('contact_email') else email
date = value('effective_date', 'To be confirmed')
year = value('copyright_year', '2026')
provider_block = '<br>'.join(part for part in [provider, address, country, contact] if part)
pages = {
 'index': ('Your Formea, with clarity.', f'''<p class="lead">Support, privacy and membership information for your Pilates practice.</p><div class="cards"><a href="privacy.html"><strong>Privacy</strong><span>What stays on your iPhone.</span></a><a href="terms.html"><strong>Terms & membership</strong><span>How access and subscriptions work.</span></a><a href="support.html"><strong>Support</strong><span>Help with your plan and purchases.</span></a></div><h2>Contact Formea</h2><p>{contact}</p>'''),
 'privacy': ('Privacy policy', f'''<p class="lead">Your workout answers and progress stay on your device. Formea does not operate a server that receives your workout history.</p><p>Effective date: {date}</p>
<h2>1. Who is responsible</h2><p>Formea is operated by the provider identified in the <a href="#provider-details">provider details</a> below. Contact us about privacy at {contact}. This policy covers the current iPhone app and these information pages.</p>
<h2>2. Information stored in the app</h2><p>The app stores your goals, focus, Pilates experience, activity level, movement preferences, workout style, routine barriers, answers saved during onboarding, selected duration, schedule, reminder choices and saved exercise substitutions. It also stores a paused workout, workout dates, actual active time, exercise completion status, selected variations, feedback, daily energy check-ins and optional ratings about movement control and breaks. Practice points and levels are calculated locally from your recorded training time and exercise completion.</p><p>These data are used locally to arrange sessions, offer appropriate variations, resume workouts and show your actual history. Matching is rule-based and runs on your iPhone. It is not a medical assessment or a remote AI analysis. No name, body photos, weight or email address is requested in the app.</p>
<h2>3. What the developer receives</h2><p>The current app has no advertising, analytics SDK, tracking identifier, developer-run backend or HealthKit integration. We do not receive your onboarding answers, energy check-ins or workout records from the app. The app does not request access to location, contacts, camera or microphone.</p>
<h2>4. Apple purchases and optional reminders</h2><p>Apple processes subscriptions and payment details. The app uses StoreKit to obtain products and verify entitlement information, including product identifiers, expiration and revocation status. Formea does not receive your card details or Apple Account password. Apple may provide the developer with sales and financial reports through App Store Connect under its own policies.</p><p>Optional reminders are scheduled locally through iOS. The system permission prompt is shown when you choose to enable reminders. You can turn them off in the app or in iPhone Settings. No remote push-notification service is used.</p>
<h2>5. Device storage, security and retention</h2><p>Your saved app state is stored in the app's iOS sandbox with system file protection. It remains until removed from the device. Device backups and device transfers may include app data according to your Apple backup settings; Formea does not provide its own cloud sync. Removing the app using Delete App removes its current local data; Offload App retains documents. Existing backups may retain older copies. Subscription cancellation and deleting the app are separate actions.</p><p>We cannot recover your local workout history from our own servers because it is not uploaded to us. Access to a phone while it is unlocked or access to your backups can expose data; keep your device and Apple Account secure.</p>
<h2>6. If you contact support</h2><p>If you email us, we receive your email address, message and attachments you choose to send, and use them to respond and resolve your request. Please do not include medical records, payment-card details, Apple Account passwords or sensitive screenshots. Support correspondence is retained only as long as necessary to handle the request, follow up, or meet applicable legal obligations. It is not used for advertising. Email delivery also involves your and our email service providers.</p>
<h2>7. Visiting these pages</h2><p>These static pages are hosted by GitHub Pages. Loading a page sends technical request information, such as your IP address and browser information, to GitHub. We have not added analytics, third-party fonts, embedded media, advertising, forms or cookies to these pages. GitHub operates the hosting platform under its <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">privacy statement</a>. GitHub and Apple may process information internationally; their policies explain their transfer safeguards. Opening their links is optional.</p>
<h2>8. Legal bases and your choices</h2><p>Where EU or UK data protection law applies, necessary service and support processing is based on performance of a contract or steps you request before a contract, legitimate interests in responding to enquiries and maintaining security, and legal obligations where applicable. Optional permissions are controlled by your choice. Local fitness records are not disclosed to the developer; avoid sending health information in support messages.</p><p>Depending on applicable law, you may request access, correction, deletion, restriction or portability of personal data we hold, object to processing based on legitimate interests, and withdraw consent where processing relies on consent. You may complain to your competent data protection authority. Contact {contact} to exercise these rights. We cannot remotely access or erase your local workout history.</p>
<h2>9. Audience and changes</h2><p>Formea is a general fitness app, not a children's service, medical service or research study. We do not knowingly collect children's data through support. If you believe a child has sent personal data, contact us. Material changes to data handling will be reflected in this policy and the app's privacy disclosures before release.</p>
<h2>10. Other providers</h2><p>For Apple's independent processing, see <a href="https://www.apple.com/legal/privacy/">Apple's privacy policy</a>. We do not sell your personal information, share your local fitness records with advertising networks, or track you across apps and websites.</p>'''),
 'terms': ('Terms & membership', f'''<p class="lead">A personal Pilates practice, with clear expectations.</p><p>Effective date: {date}. The legal provider is identified in the <a href="#provider-details">provider details</a> below. Contact: {contact}.</p>
<h2>1. App licence</h2><p>Your licence to use the iOS app is governed by <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple's Standard End User Licence Agreement</a>. These pages explain Formea's service and membership. They do not replace mandatory consumer rights or Apple's applicable purchase terms.</p>
<h2>2. What Formea provides</h2><p>Formea offers a locally personalised workout plan, selectable session duration and variations, supported exercise substitutions, optional local reminders and recorded workout progress. The current program contains 24 sessions across four chapters. Personalisation uses your selected answers and workout feedback, not a medical diagnosis. Any media available to you is the media present in the app at purchase; illustrations are not proof of exercise technique or a promised body outcome.</p>
<h2>3. Membership and billing</h2><p>A Formea Plus subscription is required to use the workouts and subscriber features. Creating a plan during onboarding does not itself buy a subscription. Available subscription periods are one week and six months. The App Store purchase sheet shows your current local price, currency, billing period and any applicable offer before confirmation. Do not assume a free trial unless the App Store explicitly offers one.</p><p>Payment is charged to your Apple Account when you confirm a purchase. Subscriptions renew automatically unless cancelled under the rules shown by Apple. Cancel renewal before the next billing date; Apple's standard renewal instructions advise at least 24 hours before the current period ends. Manage or cancel in iPhone Settings → your name → Subscriptions, or <a href="https://apps.apple.com/account/subscriptions">Apple's subscription management page</a>. Deleting Formea or its local data does not cancel billing.</p><p>Restore purchases in the app using the Apple Account that bought the subscription. Access normally continues until the end of the paid period after cancellation, subject to Apple's transaction status. An expired or revoked entitlement locks subscriber features; it does not automatically delete your local history. Purchases are handled by Apple. Request refunds through <a href="https://reportaproblem.apple.com/">Apple</a>, subject to Apple's process and applicable law.</p>
<h2>4. Movement and expectations</h2><p>Formea provides general fitness content and is not medical advice, rehabilitation, diagnosis or treatment. Choose comfortable movements, stop if you experience pain and seek appropriate professional guidance for symptoms, pregnancy, recent surgery or other conditions that may affect exercise. You can pause, use a gentler variation or stop. A plan or substitution cannot determine whether a movement is medically appropriate for you.</p><p>Results vary. We do not promise a particular waist size, weight, body shape, deadline or guaranteed transformation. Progress displays recorded activity and your own ratings; it is not an objective medical measurement. Images are illustrative and are not customer results.</p>
<h2>5. Local data and availability</h2><p>There is no Formea account. Workout history is stored locally; it does not automatically appear on a second device. Apple may restore your subscription across devices, but that is separate from syncing workout data. Device backups depend on your settings. We may update the app; no specific future video, class or feature is promised by this document.</p>
<h2>6. Your rights and support</h2><p>Nothing here removes statutory rights, remedies or liability that cannot lawfully be excluded. For help, contact {contact} or read <a href="support.html">Support</a>. Our data handling is described in the <a href="privacy.html">Privacy policy</a>.</p>'''),
 'support': ('A little help, when you need it.', f'''<p class="lead">Questions about your plan, reminders or membership?</p><h2>Contact Formea</h2><p>{contact}</p><p>Include your app version, iPhone model, iOS version and a short description of the issue. A screenshot can help, but hide personal details. Never send payment details, passwords or medical records.</p>
<h2>Change your plan</h2><p>Use Settings → My goal & starting point or Plan & reminders to change your preferences. You can also change today's duration and variation or swap a supported exercise. Your recorded history is kept when you edit a plan.</p>
<h2>Restore or cancel a subscription</h2><p>Tap Restore on the membership screen while signed into the Apple Account used for purchase. Manage or cancel renewal through <a href="https://apps.apple.com/account/subscriptions">Apple subscriptions</a>. Uninstalling the app does not cancel your subscription. For refund requests, use <a href="https://reportaproblem.apple.com/">Apple's refund service</a>.</p>
<h2>Reminders</h2><p>Check your selected days and time in Plan & reminders, then check iPhone Settings → Notifications → Formea. Focus modes can silence reminders. Reminders are optional and are scheduled locally.</p>
<h2>Workout history and device changes</h2><p>Extra sessions and short attempts are saved as separate entries. A session counts toward weekly goals and earns practice points after at least three active minutes and one completed exercise. The wind-down step does not satisfy the exercise requirement or earn an exercise bonus. For older records without exercise-level tracking, the recorded time determines eligibility. Repeating a workout adds a new entry; it does not overwrite the previous workout. Your history stays on the device and is not uploaded to a Formea server. Restoring a subscription does not restore local workout history. Apple device backups may restore data depending on your settings.</p>
<h2>Delete local data</h2><p>There is no account to delete. Use iPhone Settings → General → iPhone Storage → Formea → Delete App to remove the current local app data. Offload App keeps documents. Device backups may retain previous copies; manage them in your Apple backup settings. Cancel your subscription separately if you want billing to stop.</p>
<h2>Exercise support</h2><p>We can help with how the app works, but cannot assess pain, injury or medical suitability by email. Stop if a movement causes pain and seek qualified guidance. See <a href="terms.html">Terms & membership</a> and <a href="privacy.html">Privacy</a>.</p>''')
}
style = '''*{box-sizing:border-box}body{margin:0;background:#faf6ef;color:#443139;font-family:system-ui,-apple-system,sans-serif;line-height:1.7}header,main,footer{max-width:800px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #e3d7cf}header a{font-weight:650;text-decoration:none}nav{display:flex;gap:18px;font-size:13px}a{color:#7b3f53;text-underline-offset:4px}h1{font-family:Georgia,serif;font-weight:400;letter-spacing:-1.5px;font-size:clamp(36px,6vw,55px);line-height:1.12;margin:32px 0 24px}h2{font-size:20px;margin:36px 0 12px;line-height:1.3}.lead{font-size:19px;color:#826770}p{margin:14px 0}.draft{border:1px solid #b48262;background:#fff1df;padding:18px;border-radius:12px;font-size:14px}.cards{display:grid;gap:14px;margin:30px 0}.cards a{border:1px solid #e3d7cf;border-radius:18px;padding:20px;text-decoration:none}.cards strong,.cards span{display:block}.cards span{font-size:14px;color:#826770}footer{font-size:14px;color:#655059;border-top:1px solid #e3d7cf}footer .copyright{margin:0}footer .provider{margin-top:22px;padding-top:18px;border-top:1px solid #e3d7cf}footer h2{font-size:14px;font-weight:600;margin:0 0 8px}footer .updated{font-size:13px;margin-top:18px}@media(max-width:480px){header{display:block}nav{margin-top:12px}main{padding:20px}}'''
(root/'site').mkdir(exist_ok=True)
(root/'site/style.css').write_text(style)
(root/'site/.nojekyll').touch()
for slug, (title, body) in pages.items():
    warning = '<aside class="draft"><strong>Draft — not ready for App Store submission.</strong><br>Provider identity and public contact details must be completed before publication as the app\'s official policy.</aside>' if missing else ''
    page = f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} · Formea</title><link rel="stylesheet" href="style.css"></head><body><header><a href="index.html">formea.</a><nav aria-label="Information"><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="support.html">Support</a></nav></header><main>{warning}<h1>{title}</h1>{body}</main><footer><p class="copyright">© {year} Formea</p><section class="provider" id="provider-details" aria-labelledby="provider-heading"><h2 id="provider-heading">Provider details</h2><p>{provider_block}</p></section><p class="updated">Privacy, membership and support · Updated {date}</p></footer></body></html>'
    (root/'site'/f'{slug}.html').write_text(page)
print('Built ' + ('DRAFT: ' + ', '.join(missing) if missing else 'release-ready provider configuration'))
